version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tp2-postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - tp2-net

  neo4j:
    image: neo4j:5.20
    container_name: tp2-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_heap_initial__size: 1G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
    depends_on:
      - postgres
    networks:
      - tp2-net

  app:
    image: python:3.11-slim
    container_name: tp2-app
    working_dir: /work
    volumes:
      - ./app:/work/app
    command: >
      bash -c "pip install -r app/requirements.txt &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: shop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - neo4j
    networks:
      - tp2-net

networks:
  tp2-net: